apiVersion: v1
kind: Service
metadata:
  name: ct42
  labels:
    app: ct42
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: ct42
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: ct42
spec:
  serviceName: ct42
  replicas: 1
  selector:
    matchLabels:
      app: ct42
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ct42
    spec:
      containers:
      - name: ct42
        image: gcr.io/kubernetes-cluster-218308/ct42
        env:
        - name: LISTEN_HOST
          value: 0.0.0.0
        ports:
        - containerPort: 5000
          name: http
      - name: phantomjs
        image: gcr.io/kubernetes-cluster-218308/phantomjs
        ports:
        - containerPort: 4444
          name: http

