version: "2"
services:
  ct42:
    build: .
    environment:
      - VIRTUAL_HOST=www.ct42.cz,ct42.cz
      - LISTEN_HOST=0.0.0.0
      - LISTEN_PORT=5000
      - ENDPOINT_HOST=geckodriver
      - APP_DEBUG=0
    expose:
      - 5000
    ports:
      - 5000:5000
    links:
      - server
    restart: always

  geckodriver:
    image: instrumentisto/geckodriver
    expose:
      - 4444
    restart: always
