version: "2"
services:
  app:
    build: .
    environment:
      - VIRTUAL_HOST=www.ct42.cz,ct42.cz
      - LISTEN_HOST=0.0.0.0
      - LISTEN_PORT=8080
      - ENDPOINT_HOST=server
      - APP_DEBUG=1
    expose:
      - 8080
    ports:
      - 8080:8080
    links:
      - server
    restart: always

  server:
    image: lsde/geckodriver-firefox
    expose:
      - 4444
    restart: always
